void kleur_window_start(void);
void kleur_window_help_start(void);
void kleur_window_help_einde(void);
void kleur_window_einde(void);

int kleur_titel_normaal(void);
int kleur_titel_accent(void);

int kleur_aktiebalk_keuze(void);
int kleur_aktiebalk_mnem(void);
int kleur_aktiebalk_accent(void);

int kleur_aktiebalk_cursor(void);
int kleur_aktiebalk_cursor_mnem(void);

int kleur_body_tekst_normaal(void);
int kleur_body_tekst_accent(void);

int kleur_body_keuze_aan(void);
int kleur_body_keuze_uit(void);
int kleur_body_keuze_aan_mnem(void);
int kleur_body_keuze_uit_mnem(void);

int kleur_body_veld_normaal(void);
int kleur_body_veld_accent(void);

int kleur_pf(void);

int kleur_selektie(void);

int kleur_fout(void);

int kleur_mededeling(void);
int kleur_waarschuwing(void);
int kleur_kritiek(void);
